server:
  port: 8888

spring:
  main:
    allow-bean-definition-overriding: true

  application:
      name: avaliacao
      profile: dev

      jpa:
        database-platform: org.hibernate.dialect.H2Dialect

      # Enabling H2 Console
      h2:
        console:
          enabled: true

      datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password

logging:
    level:
        org.springframework: ERROR
        com.example: DEBUG

